config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  
  get 'welcome/index'
  get 'welcome/contact'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :entry)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="navbar navbar-fixed-bottom">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 text-center">
					<p style="padding: 5px;">The opinions expressed here are my own thoughts.<br>Copyright &copy; Mary Moody 2017</p>
				</div>
			</div>
		</div>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
            <a class="navbar-brand" href="index.html">Business Casual</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to "home", root_path%>
                </li>
                <li>
                   <%= link_to "blog", posts_path %>
                </li>
                <li>
                    <%= link_to "Contact Me", welcome_contact_path %>
                </li>
                <li>
                    <%= link_to "log in", new_user_session_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
        <!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html lang="en">

	<head>

	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <title>Mary Moody</title>

	    <!-- Rails framework functions -->
	    <%= csrf_meta_tags %>

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

	    <!-- Bootstrap Core CSS -->
	    <link rel="stylesheet" type="text/css" href="ref="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

	    <!-- Fonts -->
	    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
	    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

	    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	    <!--[if lt IE 9]>
	        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->

	</head>
	<body style="margin-left: 0px; margin-right: 0px">
		<div class="brand">Mary Moody</div>
		<div class="address-bar">221 W Poplar | San Antonio, TX 78212</div>
		<%= render 'layouts/header' %>
	    <%= yield %>
	    <%= render 'layouts/footer' %>
 	</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :entry %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center" style="color: #fff;">My Thoughts</h1>

<div class="row" style="margin: 5%; margin-bottom: 4%">
  <% @posts.each do |post| %>
    <div class="box" style="margin-bottom: 25px;">
      <hr style="margin-bottom: 1%;"><h3 class="intro-text text-center" style="margin: 0%;"><%= post.title %></h3><br> 
      <h5 class="intro-text text-center" style="margin: 0%;">by <%= post.author %></h5><hr style="margin-top: 1%;">
      <div style="padding-right: 5%; padding-left: 5%;">
        <%= post.entry %> 
      </div>
      <br><br>
      <div class="btn-group">
        <%= link_to 'Show', post, class: "btn btn-default" %>
        <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
</div>

<div style="margin-bottom: 5%">
  <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @post.entry %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-default" %>
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-default" %>
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-default" %>
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "btn btn-default" %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "btn btn-default" %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: "btn btn-default" %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
	<div class="box"  style="margin: 5%; margin-bottom: 100 px">
		<div class="col-xs-12">
			<hr><h2 class="intro-text text-center">Who I am</h2><hr>
			<p>
				I've worked, studied and played in the IT, Networking, and Information Security fields for over a decade. I enjoy gaming (computer, table top, and console), spending time with my kids, and learning new things.
				<br><br>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris sed augue laoreet, pharetra velit id, tempus arcu. Nulla facilisi. Curabitur sollicitudin tortor vel convallis eleifend. Praesent eget elit purus. Fusce porta porttitor ligula id egestas. Aenean vestibulum quam ut hendrerit vestibulum. Vivamus dictum at nulla pretium convallis. Praesent a metus sed nunc viverra dictum. Etiam a vulputate justo. Nullam ac cursus justo, vel sollicitudin enim. Maecenas consequat aliquet elit, nec hendrerit felis vestibulum egestas.
				<br><br>
				Aliquam ut ex a mi ornare commodo vitae sit amet ipsum. Praesent a lacus ac metus condimentum tempus. Nunc eleifend porta ornare. Nam et diam rhoncus, varius dui suscipit, ultrices elit. Sed mi turpis, interdum quis luctus sit amet, posuere ut mauris. Mauris felis purus, faucibus quis pulvinar quis, aliquam sed sapien. Nulla vulputate rhoncus sollicitudin. Cras hendrerit eu justo sed placerat. Etiam convallis bibendum felis vel auctor. Aliquam vitae nisi a elit efficitur facilisis. Integer a magna eget lectus aliquet tristique. In hendrerit tempus scelerisque.
				<br><br>
				Quisque et euismod ligula, eu placerat orci. Maecenas sagittis ante sit amet nisi convallis egestas. Sed at neque vel enim varius dapibus. Donec tincidunt blandit leo, quis imperdiet erat feugiat ut. Curabitur tincidunt viverra tortor, eget semper libero viverra eu. Etiam sodales vel diam quis efficitur. Proin vitae aliquet tortor. Fusce pellentesque urna sed odio finibus suscipit. Phasellus consectetur, nulla sed viverra sodales, leo diam porttitor nisi, in bibendum lectus ipsum in metus. Vivamus eu vulputate massa, ac fermentum dui. Etiam cursus fermentum leo nec fringilla. Suspendisse consequat luctus magna, eu ullamcorper dolor. Vivamus ac lorem quam.
				<br><br>
				Suspendisse vel euismod ipsum. Nam luctus orci at lectus porta elementum. Duis ac lorem ac ligula fringilla mattis. Praesent tincidunt ipsum libero, sed viverra augue aliquam sed. Sed vitae ligula non turpis iaculis hendrerit. Praesent ornare leo quis est varius hendrerit vitae ut enim. Aliquam at enim nec eros aliquam eleifend sit amet id tortor.
				<br><br>
				Curabitur dignissim et urna vehicula interdum. Etiam convallis imperdiet luctus. Sed lobortis neque in leo sodales, quis condimentum enim imperdiet. In arcu leo, ultrices quis sem eget, imperdiet suscipit justo. Mauris eleifend sem nulla. Donec condimentum euismod dignissim. Curabitur mauris nunc, bibendum ut metus et, mattis bibendum orci. Donec nec diam arcu. Praesent eu libero non velit consectetur iaculis elementum non elit. Curabitur volutpat dapibus mauris non tempor. Donec tincidunt, orci auctor varius congue, mauris leo fringilla nisi, eu feugiat purus elit non sapien. Etiam mollis turpis quam, non vehicula eros porta non. Quisque nisi enim, pretium ut tristique a, tristique in velit. Praesent egestas id sapien eu vehicula.
				<br><br>
				Nunc leo quam, porta at luctus sit amet, consectetur et massa. Vivamus mattis dapibus nunc, a suscipit urna ornare vel. Nullam maximus malesuada blandit. Morbi nec velit feugiat, feugiat.
			</p>
		</div>
	</div>